services:
  server:
    build: ./server
    ports: 
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  logs:
